import './global.css';
import { Navbar } from './navbar/navbar';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Welcome to goku',
  description: 'Generated by create-nx-workspace',
};

interface MenuItem {
  name: string;
  href: string;
}
const menuItems: MenuItem[] = [
  { name: "Inicio", href: "/" },
  { name: "DBZ", href: "/goku" },
  { name: "Comunidades", href: "/comunidades" },
  { name: "Cuadrantes", href: "/cuadrantes" },
  { name: "Vacaciones", href: "/vacaciones" },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar menuItems={menuItems} />
        <main className="mx-auto max-w-[1400px] pt-16 px-6">
          {children}
        </main>
      </body>
        
    </html>
  );
}
